update io to fix 'ns io not found'

diff --git a/config/instana-new/charts/instana-operator/templates/pre-install-job.yaml b/config/instana-new/charts/instana-operator/templates/pre-install-job.yaml
--- a/config/instana-new/charts/instana-operator/templates/pre-install-job.yaml
+++ b/config/instana-new/charts/instana-operator/templates/pre-install-job.yaml
@@ -38,14 +38,14 @@ spec:
               # fi
 
               # ns 
-              echo 'Check namespace "instana-operator" '
-              oc get ns instana-operator
-              if [[ $? != 0 ]]; then
-                 echo 'Namespace "instana-operator" not found, now create it.'
-                 oc create ns instana-operator 
-              else
-                 echo 'Namespace "instana-operator" found.'
-              fi
+              echo 'create namespace "instana-operator" '
+              # oc get ns instana-operator
+              # if [[ $? != 0 ]]; then
+              #    echo 'Namespace "instana-operator" not found, now create it.'
+              oc create ns instana-operator 
+              # else
+              #    echo 'Namespace "instana-operator" found.'
+              # fi
 
               # imagePullSecrets ?
               echo "create secret instana-registry "
