add wait func

diff --git a/instana-automatic/instana-ocp/00-presync-job.yaml b/instana-automatic/instana-ocp/00-presync-job.yaml
--- a/instana-automatic/instana-ocp/00-presync-job.yaml
+++ b/instana-automatic/instana-ocp/00-presync-job.yaml
@@ -25,18 +25,45 @@ spec:
               set -x
               result=0
 
+              while : ; do
+                oc get sa instana-core -n instana-core
+                if [[ $? != 0 ]]; then
+                  echo 'Serviceaccount "instana-core" not found in namespace instana-core'
+                  sleep 10s
+                else 
+                  break
+                fi
+              done
               oc adm policy add-scc-to-user anyuid -z instana-core -n instana-core
               result=$?
               if [[ ${result} != 0 ]]; then 
                 exit "${result}"
               fi
 
+              while : ; do
+                oc get sa default -n instana-core
+                if [[ $? != 0 ]]; then
+                  echo 'Serviceaccount "default" not found in namespace instana-core'
+                  sleep 10s
+                else 
+                  break
+                fi
+              done
               oc adm policy add-scc-to-user anyuid -z default -n instana-core
               result=$?
               if [[ ${result} != 0 ]]; then 
                 exit "${result}"
               fi
 
+              while : ; do
+                oc get sa default -n instana-units
+                if [[ $? != 0 ]]; then
+                  echo 'Serviceaccount "default" not found in namespace instana-units'
+                  sleep 10s
+                else 
+                  break
+                fi
+              done
               oc adm policy add-scc-to-user anyuid -z default -n instana-units
               result=$?
               if [[ ${result} != 0 ]]; then 
diff --git a/instana-automatic/instana-ocp/99-postsync-job.yaml b/instana-automatic/instana-ocp/99-postsync-job.yaml
--- a/instana-automatic/instana-ocp/99-postsync-job.yaml
+++ b/instana-automatic/instana-ocp/99-postsync-job.yaml
@@ -28,6 +28,16 @@ spec:
               base=`oc get ingresses.config/cluster -o jsonpath={.spec.domain}`
               echo ${base}
 
+              while : ; do
+                oc get ns instana-core
+                if [[ $? != 0 ]]; then
+                  echo 'Namespace "instana-core" not found'
+                  sleep 10s
+                else 
+                  break
+                fi
+              done
+
               cat << EOF | oc apply -f -
               apiVersion: route.openshift.io/v1
               kind: Route
@@ -74,6 +84,15 @@ spec:
                 exit "${result}"
               fi                            
 
+              while : ; do
+                oc get ns instana-units
+                if [[ $? != 0 ]]; then
+                  echo 'Namespace "instana-units" not found'
+                  sleep 10s
+                else 
+                  break
+                fi
+              done
               cat << EOF | oc apply -f -
               apiVersion: route.openshift.io/v1
               kind: Route
